/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankAccount {
  'routingNumber' : string,
  'accountHolderName' : string,
  'bankName' : string,
  'accountNumber' : string,
}
export interface CartItem { 'item' : SnackItem, 'quantity' : bigint }
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'customerPhone' : string,
  'customerAddress' : string,
  'totalAmount' : bigint,
  'items' : Array<CartItem>,
  'customerEmail' : string,
}
export interface SnackItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBankAccount' : ActorMethod<[string, string, string, string], string>,
  'addSnackItem' : ActorMethod<
    [string, string, string, bigint, ExternalBlob],
    undefined
  >,
  'addToCart' : ActorMethod<[string, string, bigint], undefined>,
  'checkout' : ActorMethod<[string, string, string, string, string], bigint>,
  'clearCart' : ActorMethod<[string], boolean>,
  'deleteSnackItem' : ActorMethod<[string], boolean>,
  'getAdminOrderManagement' : ActorMethod<[], Array<Order>>,
  'getAllBankAccounts' : ActorMethod<[], Array<BankAccount>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllSnackItems' : ActorMethod<[], Array<SnackItem>>,
  'getBankAccount' : ActorMethod<[string], [] | [BankAccount]>,
  'getCart' : ActorMethod<[string], Array<CartItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getSnackItem' : ActorMethod<[string], [] | [SnackItem]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];